# Generated by Django 4.2 on 2023-04-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covertype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Elevation', models.FloatField()),
                ('Aspect', models.FloatField()),
                ('Slope', models.FloatField()),
                ('Horizontal_Distance_To_Hydrology', models.FloatField()),
                ('Vertical_Distance_To_Hydrology', models.FloatField()),
                ('Horizontal_Distance_To_Roadways', models.FloatField()),
                ('Hillshade_9am', models.FloatField()),
                ('Hillshade_Noon', models.FloatField()),
                ('Hillshade_3pm', models.FloatField()),
                ('Horizontal_Distance_To_Fire_Points', models.FloatField()),
                ('Wilderness_Area_1', models.BooleanField()),
                ('Wilderness_Area_2', models.BooleanField()),
                ('Wilderness_Area_3', models.BooleanField()),
                ('Wilderness_Area_4', models.BooleanField()),
                ('Soil_Type_1', models.BooleanField()),
                ('Soil_Type_2', models.BooleanField()),
                ('Soil_Type_3', models.BooleanField()),
                ('Soil_Type_4', models.BooleanField()),
                ('Soil_Type_5', models.BooleanField()),
                ('Soil_Type_6', models.BooleanField()),
                ('Soil_Type_7', models.BooleanField()),
                ('Soil_Type_8', models.BooleanField()),
                ('Soil_Type_9', models.BooleanField()),
                ('Soil_Type_10', models.BooleanField()),
                ('Soil_Type_11', models.BooleanField()),
                ('Soil_Type_12', models.BooleanField()),
                ('Soil_Type_13', models.BooleanField()),
                ('Soil_Type_14', models.BooleanField()),
                ('Soil_Type_15', models.BooleanField()),
                ('Soil_Type_16', models.BooleanField()),
                ('Soil_Type_17', models.BooleanField()),
                ('Soil_Type_18', models.BooleanField()),
                ('Soil_Type_19', models.BooleanField()),
                ('Soil_Type_20', models.BooleanField()),
                ('Soil_Type_21', models.BooleanField()),
                ('Soil_Type_22', models.BooleanField()),
                ('Soil_Type_23', models.BooleanField()),
                ('Soil_Type_24', models.BooleanField()),
                ('Soil_Type_25', models.BooleanField()),
                ('Soil_Type_26', models.BooleanField()),
                ('Soil_Type_27', models.BooleanField()),
                ('Soil_Type_28', models.BooleanField()),
                ('Soil_Type_29', models.BooleanField()),
                ('Soil_Type_30', models.BooleanField()),
                ('Soil_Type_31', models.BooleanField()),
                ('Soil_Type_32', models.BooleanField()),
                ('Soil_Type_33', models.BooleanField()),
                ('Soil_Type_34', models.BooleanField()),
                ('Soil_Type_35', models.BooleanField()),
                ('Soil_Type_36', models.BooleanField()),
                ('Soil_Type_37', models.BooleanField()),
                ('Soil_Type_38', models.BooleanField()),
                ('Soil_Type_39', models.BooleanField()),
                ('Soil_Type_40', models.BooleanField()),
                ('Cover_Type', models.IntegerField()),
            ],
        ),
    ]
